version: '3'

volumes:
  static:
  backend_static:
  backend_media:
  postgres_data:

services:


  frontend:
    build: ../frontend
#    image: kda99/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
      - static:/app/result_build/build

  nginx:
#    build: ../infra
    image: nginx:1.25.2-alpine
#    image: kda99/foodgram_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - backend_static:/backend_static
      - backend_media:/backend_media
      - ../docs/:/usr/share/nginx/html/api/docs/

  db:
    image: postgres:13.10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build: ../backend/foodgram
#    image: kda99/foodgram_backend
    restart: always
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media
    depends_on:
      - db
    env_file:
      - ./.env
