version: '3'

volumes:
  static:
  backend_static:
  backend_media:
  postgres_data:

services:


  backend:
#    image: kda99/foodgram_backend
    build: ../backend/foodgram
    restart: always
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: kda99/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
      - static:/app/result_build/build

  nginx:
    image: kda99/foodgram_gateway
#    image: nginx:1.22.1
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - backend_static:/backend_static
      - backend_media:/backend_media
      - ../docs/:/usr/share/nginx/html/api/docs/

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
